# Generated by Django 5.2.6 on 2025-09-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=1)),
            ],
        ),
    ]
