# Generated by Django 5.2.6 on 2025-09-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinador',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
