# Generated by Django 5.2.6 on 2025-09-12 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sprite', models.URLField()),
                ('tipos', models.CharField(max_length=200)),
                ('stats', models.JSONField()),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='treinadores.treinador')),
            ],
        ),
    ]
